(* 14.BNF - A simple set of productions with some alternatives
   and null productions *)

Lecturer  = FirstName Surname Degrees.
FirstName = ( "Dr" | "Professor" | "Ms" |   ) ( "K.L." | "Karen") .
Surname   = "Bradshaw" .
Degrees   = "PhD" |   .
