  Calc

  = { Variable
      "=" Expression

    } EOF .

  Expression
  = Term
    {   "+" Term
      | "-" Term
    } .

  Term
  = Factor
    {   "*" Factor
      | "/" Factor
    } .

  Factor
  =   Number

    | Variable

    | "(" Expression ")"
    .

